module.exports = [
    {
        question: "What’s the shortcut for the “copy” function on most computers?",
        answer1: "CTRL+C",
        answer2: "CTRL+V",
        answer3: "CTRL+A",
        answer4: "CTRL+Z",
        correctAnswer: "1",
        winningPrize: "1",
    },
    {
        question: "What is the name of the jelly like substance inside of cells that is responsible for holding the organelles in place",
        answer1: "Your mom",
        answer2: "Cytoplasm",
        answer3: "Ectoplasm",
        answer4: "Ribosomes",
        correctAnswer: "2",
        winningPrize: "1",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
    {
        question: "",
        answer1: "",
        answer2: "",
        answer3: "",
        answer4: "",
        correctAnswer: "",
        winningPrize: "",
    },
]